version: 1.0.{build}
image: Visual Studio 2017
install:
  - dotnet restore
  - cd .\KnockoutExample\
  - npm install
  - npm install -g webpack mocha chai ts-node
  - webpack --config webpack.config.vendor.js -p
  - webpack -p
  - npm test
build:
  verbosity: minimal
#after_build:
#- cmd: dotnet publish KnockoutExample --output %appveyor_build_folder%\dist