version: 1.0.{build}
install:
  - dotnet restore
  - cd .\KnockoutExample\
  - npm install
  - npm install -g webpack
  - webpack --config webpack.config.vendor.js
  - webpack -d
build:
  verbosity: minimal
after_build:
- cmd: dotnet publish KnockoutExample --output %appveyor_build_folder%\dist