version 1.0.{build}

install:
- cmd: >-
  dotnet restore
  npm install
  webpack --config webpack.config.vendor.js
  webpack -d
build:
  verbosity: minimal
after_build:
- cmd: dotnet publish src\KnockoutExample --output %appveyor_build_folder%\dist